// 더미 데이터

export interface Content {
  id: string;
  title: string;
  author: string;
  type: "SHORTS" | "SUMMARY" | "AUDIO" | "NOVEL";
  genre: string;
  language: string;
  thumbnail: string;
  rating: string;
  price: number;
  views: number;
  likes: number;
  createdAt: string;
}

export interface Playlist {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  contentCount: number;
  createdAt: string;
}

export const mockContents: Content[] = [
  {
    id: "1",
    title: "액션 숏폼",
    author: "작가 A",
    type: "SHORTS",
    genre: "액션",
    language: "KO",
    thumbnail: "/thumbnails/shorts-1.svg",
    rating: "15+",
    price: 0,
    views: 12345,
    likes: 567,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    title: "인기 오디오북",
    author: "작가 B",
    type: "AUDIO",
    genre: "로맨스",
    language: "KO",
    thumbnail: "/thumbnails/audio-1.svg",
    rating: "12+",
    price: 0,
    views: 23456,
    likes: 890,
    createdAt: "2024-01-14",
  },
  {
    id: "3",
    title: "요약 영상 시리즈",
    author: "작가 C",
    type: "SUMMARY",
    genre: "드라마",
    language: "KO",
    thumbnail: "/thumbnails/summary-1.svg",
    rating: "15+",
    price: 0,
    views: 34567,
    likes: 1234,
    createdAt: "2024-01-13",
  },
  {
    id: "4",
    title: "웹소설 베스트",
    author: "작가 D",
    type: "NOVEL",
    genre: "판타지",
    language: "KO",
    thumbnail: "/thumbnails/novel-1.svg",
    rating: "12+",
    price: 0,
    views: 45678,
    likes: 2345,
    createdAt: "2024-01-12",
  },
  {
    id: "5",
    title: "코미디 숏폼",
    author: "작가 E",
    type: "SHORTS",
    genre: "코미디",
    language: "KO",
    thumbnail: "/thumbnails/shorts-2.svg",
    rating: "ALL",
    price: 0,
    views: 56789,
    likes: 3456,
    createdAt: "2024-01-11",
  },
  {
    id: "6",
    title: "스릴러 오디오북",
    author: "작가 F",
    type: "AUDIO",
    genre: "스릴러",
    language: "KO",
    thumbnail: "/thumbnails/audio-2.svg",
    rating: "19+",
    price: 0,
    views: 67890,
    likes: 4567,
    createdAt: "2024-01-10",
  },
  {
    id: "7",
    title: "액션 요약 영상",
    author: "작가 G",
    type: "SUMMARY",
    genre: "액션",
    language: "EN",
    thumbnail: "/thumbnails/summary-2.svg",
    rating: "15+",
    price: 0,
    views: 78901,
    likes: 5678,
    createdAt: "2024-01-09",
  },
  {
    id: "8",
    title: "로맨스 웹소설",
    author: "작가 H",
    type: "NOVEL",
    genre: "로맨스",
    language: "KO",
    thumbnail: "/thumbnails/novel-2.svg",
    rating: "12+",
    price: 0,
    views: 89012,
    likes: 6789,
    createdAt: "2024-01-08",
  },
  {
    id: "9",
    title: "로맨스 숏폼",
    author: "작가 I",
    type: "SHORTS",
    genre: "로맨스",
    language: "KO",
    thumbnail: "/thumbnails/shorts-3.svg",
    rating: "12+",
    price: 0,
    views: 90123,
    likes: 7890,
    createdAt: "2024-01-07",
  },
  {
    id: "10",
    title: "판타지 숏폼",
    author: "작가 J",
    type: "SHORTS",
    genre: "판타지",
    language: "KO",
    thumbnail: "/thumbnails/shorts-4.svg",
    rating: "12+",
    price: 0,
    views: 101234,
    likes: 8901,
    createdAt: "2024-01-06",
  },
  {
    id: "11",
    title: "로맨스 요약 영상",
    author: "작가 K",
    type: "SUMMARY",
    genre: "로맨스",
    language: "KO",
    thumbnail: "/thumbnails/summary-3.svg",
    rating: "12+",
    price: 0,
    views: 112345,
    likes: 9012,
    createdAt: "2024-01-05",
  },
  {
    id: "12",
    title: "판타지 요약 영상",
    author: "작가 L",
    type: "SUMMARY",
    genre: "판타지",
    language: "KO",
    thumbnail: "/thumbnails/summary-4.svg",
    rating: "12+",
    price: 0,
    views: 123456,
    likes: 10123,
    createdAt: "2024-01-04",
  },
  {
    id: "13",
    title: "판타지 오디오북",
    author: "작가 M",
    type: "AUDIO",
    genre: "판타지",
    language: "KO",
    thumbnail: "/thumbnails/audio-3.svg",
    rating: "12+",
    price: 0,
    views: 134567,
    likes: 11234,
    createdAt: "2024-01-03",
  },
  {
    id: "14",
    title: "드라마 오디오북",
    author: "작가 N",
    type: "AUDIO",
    genre: "드라마",
    language: "KO",
    thumbnail: "/thumbnails/audio-4.svg",
    rating: "15+",
    price: 0,
    views: 145678,
    likes: 12345,
    createdAt: "2024-01-02",
  },
  {
    id: "15",
    title: "액션 웹소설",
    author: "작가 O",
    type: "NOVEL",
    genre: "액션",
    language: "KO",
    thumbnail: "/thumbnails/novel-3.svg",
    rating: "15+",
    price: 0,
    views: 156789,
    likes: 13456,
    createdAt: "2024-01-01",
  },
  {
    id: "16",
    title: "스릴러 웹소설",
    author: "작가 P",
    type: "NOVEL",
    genre: "스릴러",
    language: "KO",
    thumbnail: "/thumbnails/novel-4.svg",
    rating: "19+",
    price: 0,
    views: 167890,
    likes: 14567,
    createdAt: "2023-12-31",
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: "1",
    title: "내 플레이리스트 1",
    description: "좋아하는 콘텐츠 모음",
    thumbnail: "/thumbnails/shorts-1.svg",
    contentCount: 12,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    title: "주말 감상용",
    description: "주말에 볼 만한 콘텐츠",
    thumbnail: "/thumbnails/audio-1.svg",
    contentCount: 8,
    createdAt: "2024-01-10",
  },
];

export const mockAdminContent = [
  { id: 1001, title: "콘텐츠 제목 1", type: "SUMMARY_VIDEO", status: "게시", views: 1234, createdAt: "2024-01-15" },
  { id: 1002, title: "콘텐츠 제목 2", type: "AUDIO", status: "검수중", views: 567, createdAt: "2024-01-14" },
  { id: 1003, title: "콘텐츠 제목 3", type: "SHORTS", status: "게시", views: 8901, createdAt: "2024-01-13" },
  { id: 1004, title: "콘텐츠 제목 4", type: "NOVEL", status: "작성중", views: 0, createdAt: "2024-01-12" },
  { id: 1005, title: "콘텐츠 제목 5", type: "SUMMARY_VIDEO", status: "게시", views: 2345, createdAt: "2024-01-11" },
  { id: 1006, title: "콘텐츠 제목 6", type: "AUDIO", status: "게시", views: 6789, createdAt: "2024-01-10" },
  { id: 1007, title: "콘텐츠 제목 7", type: "SHORTS", status: "검수중", views: 123, createdAt: "2024-01-09" },
  { id: 1008, title: "콘텐츠 제목 8", type: "NOVEL", status: "게시", views: 4567, createdAt: "2024-01-08" },
];

export const mockSettlement = [
  { period: "2024-01", content: "콘텐츠 A", revenue: 1000000, share: 0.7, amount: 700000 },
  { period: "2024-01", content: "콘텐츠 B", revenue: 2000000, share: 0.6, amount: 1200000 },
  { period: "2024-01", content: "콘텐츠 C", revenue: 1500000, share: 0.8, amount: 1200000 },
];

